## python libraries for data sciences
     ->numpy
     ->pandas
     ->matplot library

#### NUMPY

In [4]:
import numpy as np
np.__version__


'1.16.5'

In [2]:
np.array([1,2,3]) # creating using list

array([1, 2, 3])

In [3]:
np.array((1,2,3)) # creating using tuple

array([1, 2, 3])

In [7]:
np.array([[1,2,3],[4,5,6]])  # 2 dimesional

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a=np.array([[[1,2,3],[4,5,6],[5,6,7],[0,0,0]]])


In [60]:
# ndim - returns dimensions of array
a.ndim

4

In [61]:
# size - returns size of of array(nof elemnts)
a.size

12

In [62]:
# shape - returns dimesnions of array


a.shape 

(1, 1, 4, 3)

In [63]:
# dtype returns systems config
a.dtype

dtype('int32')

In [67]:
# item size - returns size of element used in bytes
a.itemsize

4

In [71]:
# arange - we can craete the size of arrays to be used
np.arange(1,10) # if no starting addres is specified starts with 0

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(1,50,2) # last variable represent increment size


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [74]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [76]:
# reshape(colum,rows) - used to reshape the array dimensions
np.arange(0,24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [80]:
# linspace(start ,end ,nof partitions)- creates array diveded into specified nof partition
np.linspace(1,10)

array([ 1. ,  5.5, 10. ])

In [82]:
# random creates random values 
np.random.randint(1,20,4)# generates 4 values bw 1 and 20


array([11, 10, 15,  7])

In [83]:
np.random.randint(1,10,(5,4)) # (5,4) represent rows,col

array([[9, 1, 8, 5],
       [9, 7, 6, 6],
       [6, 4, 7, 3],
       [3, 9, 7, 4],
       [3, 5, 2, 5]])

In [87]:
# randn -returns values of random distribution curves
np.random.randn(5)

array([ 0.51244912,  0.52842583, -0.99877363,  1.09146395, -0.03055656])

In [88]:
np.random.randn(3,5)# row ,col

array([[-0.92448381, -0.25346923,  1.46361409, -0.04484912,  1.30201774],
       [ 0.03658649,  1.02983092,  0.59979348, -1.51062454, -0.5083422 ],
       [-0.32898941,  0.92878526, -0.30497384,  2.17367984,  0.6647691 ]])

In [91]:
np.random.random((3,2))

array([[0.89941217, 0.70532117],
       [0.4961578 , 0.62434518],
       [0.95848039, 0.93891345]])

In [96]:
help("random")

Help on module random:

NAME
    random - Random variable generators.

DESCRIPTION
        integers
        --------
               uniform within range
    
        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation
    
        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               lognormal
               negative exponential
               gamma
               beta
               pareto
               Weibull
    
        distributions on the circle (angles 0 to 2pi)
        ---------------------------------------------
               circular uniform
               von Mises
    
    General notes on the underlying Mersenne Twister core generator:
    
    * The period is 2**19937-1.
    * It is one of the most extensively tested generators

In [100]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [101]:
1/8e3

0.000125

In [105]:
np.linspace(0,0.000125,3)

array([0.00e+00, 6.25e-05, 1.25e-04])

# array initialiszation
    ->np.ones
    ->np.zeros
    ->np.diag
    ->np.full

In [112]:
#np.ones((nof matrices,rows,col))
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [113]:
np.zeros((4,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [114]:
np.diag((54,5,6)) # prints the given elements in array diagnolly 

array([[54,  0,  0],
       [ 0,  5,  0],
       [ 0,  0,  6]])

In [115]:
# np.full((rows,cols),value)
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

##  slicing
    -> similar to lists slicing

In [3]:
a=np.arange(20)
print(a)
a[1:3]

NameError: name 'np' is not defined

In [119]:
# reversing
a[::-1] 

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [122]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
b=np.arange(25).reshape(5,5)

In [132]:
b[1:4] # prints from 2 col onwards

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
print(b)
b[1:5,2:4] # print col 1 to 5 ,col 2to4 #prints start pos ,n-1 pos

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [137]:
b[1,2] # colum 1 and 2n elemnt

7

In [142]:
b[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [15]:
# alternate elemnts
b[1:5:2,1:5:2]

array([[ 6,  8],
       [16, 18]])

In [20]:
a=np.arange(0,25).reshape(5,5)

In [21]:
a[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [67]:
a[[1,2],[3,4]] # (row1,reow2)(col1,col2)

array([ 8, 14,  7])

# pandas
    -> used for data processing
    ->datastructers
        ->series (print serially)
        ->data frames(prints in tabular form)

In [2]:
import pandas as pd
pd.__version__



'0.25.1'

In [3]:
# Series
pd.Series([1,2,3,4]) # prints serially att the same time assigns index automativcally

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
# giving index manually 
a=pd.Series([1,2,3,4,5,6,7,8],index=["s","r","i","m","a","n","j","a"])

In [25]:
print(a["s"])
a["s":"i"]

1


s    1
r    2
i    3
dtype: int64

In [33]:
import numpy as np
a=np.arange(1,6)
pd.Series(a)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [37]:
# date_range(start ,end date) -used to print dates between ranges
pd.date_range("20-10-2200","25-10-2200")

DatetimeIndex(['2200-10-20', '2200-10-21', '2200-10-22', '2200-10-23',
               '2200-10-24', '2200-10-25'],
              dtype='datetime64[ns]', freq='D')

In [38]:
pd.date_range("20-10-2200",periods=4)#periods =cnt to be started 

DatetimeIndex(['2200-10-20', '2200-10-21', '2200-10-22', '2200-10-23'], dtype='datetime64[ns]', freq='D')

# data frames
     -> prints in tabular form

In [43]:
sm={"name":["a","b","c"],"marks":[1,2,3],"sub":["c","java","python"],"cgpa":[8.38,8.91,8.48]}

In [44]:
sm

{'name': ['a', 'b', 'c'],
 'marks': [1, 2, 3],
 'sub': ['c', 'java', 'python'],
 'cgpa': [8.38, 8.91, 8.48]}

In [45]:
pd.DataFrame(sm)# assign index manually

name  marks     sub  cgpa
0    a      1       c  8.38
1    b      2    java  8.91
2    c      3  python  8.48

In [49]:
pd.DataFrame(sm,index=["id1","id2","id3"])

name  marks     sub  cgpa
id1    a      1       c  8.38
id2    b      2    java  8.91
id3    c      3  python  8.48

In [50]:
# read a csv file csv=com a seperated values
data=pd.read_csv("Lifeexpectancy.csv")#pd.read_csv("paths") and assigns index values automatically


In [51]:
data

population  fertility   HIV        CO2  BMI_male      GDP  BMI_female  \
0    34811059.0       2.73   0.1   3.328945  24.59620  12314.0    129.9049   
1    19842251.0       6.43   2.0   1.474353  22.25083   7103.0    130.1247   
2    40381860.0       2.24   0.5   4.785170  27.50170  14646.0    118.8915   
3     2975029.0       1.40   0.1   1.804106  25.35542   7383.0    132.8108   
4    21370348.0       1.96   0.1  18.016313  27.56373  41312.0    117.3755   
..          ...        ...   ...        ...       ...      ...         ...   
134   3350832.0       2.11   0.5   2.489764  26.39123  15317.0    124.2604   
135  26952719.0       2.46   0.1   4.476669  25.32054   3733.0    124.3462   
136  86589342.0       1.86   0.4   1.479347  20.91630   4085.0    121.9367   
137  13114579.0       5.88  13.6   0.148982  20.68321   3039.0    132.4493   
138  13495462.0       3.85  15.1   0.654323  22.02660   1286.0    131.9745   

     life  child_mortality                      Region  
0    75.3             29.5  Middle East & North Africa  
1    58.3            192.0          Sub-Saharan Africa  
2    75.5             15.4                     America  
3    72.5             20.0       Europe & Central Asia  
4    81.5              5.2         East Asia & Pacific  
..    ...              ...                         ...  
134  76.0             13.0                     America  
135  68.7             49.2       Europe & Central Asia  
136  75.4             26.2         East Asia & Pacific  
137  52.0             94.9          Sub-Saharan Africa  
138  49.0             98.3          Sub-Saharan Africa  

[139 rows x 10 columns]

In [52]:
# shape -retuns size
data.shape

(139, 10)

In [55]:
# head - used to rprint the specified nof rows
data.head(20) # idf size not mentioned defaulty primts 5 rows

population  fertility    HIV        CO2  BMI_male      GDP  BMI_female  \
0    34811059.0       2.73   0.10   3.328945  24.59620  12314.0    129.9049   
1    19842251.0       6.43   2.00   1.474353  22.25083   7103.0    130.1247   
2    40381860.0       2.24   0.50   4.785170  27.50170  14646.0    118.8915   
3     2975029.0       1.40   0.10   1.804106  25.35542   7383.0    132.8108   
4    21370348.0       1.96   0.10  18.016313  27.56373  41312.0    117.3755   
5     8331465.0       1.41   0.30   8.183160  26.46741  43952.0    124.1394   
6     8868713.0       1.99   0.10   5.109538  25.65117  14365.0    128.6024   
7      348587.0       1.89   3.10   3.131921  27.24594  24373.0    124.3862   
8   148252473.0       2.38   0.06   0.319161  20.39742   2265.0    125.0307   
9      277315.0       1.83   1.30   6.008279  26.38439  16075.0    126.3940   
10    9526453.0       1.42   0.20   6.488174  26.16443  14488.0    129.7968   
11   10779155.0       1.82   0.20   9.797337  26.75915  41641.0    121.8227   
12     306165.0       2.91   2.40   1.360126  27.02255   8293.0    120.9224   
13    8973525.0       5.27   1.20   0.537539  22.41835   1646.0    130.2723   
14     694990.0       2.51   0.20   0.601210  22.82180   5663.0    125.1258   
15    9599916.0       3.48   0.20   1.431829  24.43335   5066.0    122.4155   
16    1967866.0       2.86  24.90   2.547205  22.12984  13858.0    133.1307   
17  194769696.0       1.90   0.45   2.023773  25.78623  13906.0    124.8745   
18    7513646.0       1.43   0.10   6.690139  26.54286  15368.0    128.4721   
19   14709011.0       6.04   1.20   0.109419  21.27157   1358.0    130.6651   

    life  child_mortality                      Region  
0   75.3             29.5  Middle East & North Africa  
1   58.3            192.0          Sub-Saharan Africa  
2   75.5             15.4                     America  
3   72.5             20.0       Europe & Central Asia  
4   81.5              5.2         East Asia & Pacific  
5   80.4              4.6       Europe & Central Asia  
6   70.6             43.3       Europe & Central Asia  
7   72.2             14.5                     America  
8   68.4             55.9                  South Asia  
9   75.3             15.4                     America  
10  70.1              7.2       Europe & Central Asia  
11  79.4              4.7       Europe & Central Asia  
12  70.7             20.1                     America  
13  63.2            116.3          Sub-Saharan Africa  
14  67.6             48.1                  South Asia  
15  70.9             52.0                     America  
16  61.2             63.8          Sub-Saharan Africa  
17  73.9             18.6                     America  
18  73.2             13.7       Europe & Central Asia  
19  59.4            130.4          Sub-Saharan Africa

In [57]:
# tail (cnt(nof rows))- used to return specified nof value sfrom last
data.tail(10) #if size not mentiond defaultly prints 5 values 

population  fertility    HIV        CO2  BMI_male      GDP  BMI_female  \
129   70344357.0       2.15   0.06   4.021903  26.70371  16454.0    124.0675   
130   31014427.0       6.34   6.40   0.100853  22.35833   1437.0    134.5204   
131   46028476.0       1.38   1.10   7.032359  25.42379   8762.0    131.4962   
132   61689620.0       1.87   0.20   8.526467  27.39249  37739.0    124.0845   
133  304473143.0       2.07   0.60  18.545992  28.45698  50384.0    118.4777   
134    3350832.0       2.11   0.50   2.489764  26.39123  15317.0    124.2604   
135   26952719.0       2.46   0.10   4.476669  25.32054   3733.0    124.3462   
136   86589342.0       1.86   0.40   1.479347  20.91630   4085.0    121.9367   
137   13114579.0       5.88  13.60   0.148982  20.68321   3039.0    132.4493   
138   13495462.0       3.85  15.10   0.654323  22.02660   1286.0    131.9745   

     life  child_mortality                 Region  
129  75.1             22.2  Europe & Central Asia  
130  57.2             89.3     Sub-Saharan Africa  
131  68.2             12.9  Europe & Central Asia  
132  79.5              5.6  Europe & Central Asia  
133  78.2              7.7                America  
134  76.0             13.0                America  
135  68.7             49.2  Europe & Central Asia  
136  75.4             26.2    East Asia & Pacific  
137  52.0             94.9     Sub-Saharan Africa  
138  49.0             98.3     Sub-Saharan Africa

In [62]:
# sample - used to return a random row
data.sample(3) # randomly gives the specified nof rows ,if no size given defaultly retuns 1 row

population  fertility  HIV       CO2  BMI_male      GDP  BMI_female  life  \
19  14709011.0       6.04  1.2  0.109419  21.27157   1358.0    130.6651  59.4   
61   4480145.0       2.00  0.2  9.882531  27.65325  47713.0    124.7801  79.4   
83   4111168.0       1.49  0.4  1.313321  24.23690   3890.0    129.9424  69.6   

    child_mortality                 Region  
19            130.4     Sub-Saharan Africa  
61              4.5  Europe & Central Asia  
83             17.6  Europe & Central Asia

In [63]:
data.columns # retuns column values

Index(['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP',
       'BMI_female', 'life', 'child_mortality', 'Region'],
      dtype='object')

In [65]:
data.index # returns index values

RangeIndex(start=0, stop=139, step=1)

In [66]:
data.dtypes # returns data types of the columns 

population         float64
fertility          float64
HIV                float64
CO2                float64
BMI_male           float64
GDP                float64
BMI_female         float64
life               float64
child_mortality    float64
Region              object
dtype: object

In [76]:
data.notnull() # returns if colm is empty

population  fertility   HIV   CO2  BMI_male   GDP  BMI_female  life  \
0          True       True  True  True      True  True        True  True   
1          True       True  True  True      True  True        True  True   
2          True       True  True  True      True  True        True  True   
3          True       True  True  True      True  True        True  True   
4          True       True  True  True      True  True        True  True   
..          ...        ...   ...   ...       ...   ...         ...   ...   
134        True       True  True  True      True  True        True  True   
135        True       True  True  True      True  True        True  True   
136        True       True  True  True      True  True        True  True   
137        True       True  True  True      True  True        True  True   
138        True       True  True  True      True  True        True  True   

     child_mortality  Region  
0               True    True  
1               True    True  
2               True    True  
3               True    True  
4               True    True  
..               ...     ...  
134             True    True  
135             True    True  
136             True    True  
137             True    True  
138             True    True  

[139 rows x 10 columns]

In [83]:
data.describe() # returns count,max valu,sum,mean,deviation of the values

population   fertility         HIV         CO2    BMI_male  \
count  1.390000e+02  139.000000  139.000000  139.000000  139.000000   
mean   3.549977e+07    3.005108    1.915612    4.459874   24.623054   
std    1.095121e+08    1.615354    4.408974    6.268349    2.209368   
min    2.773150e+05    1.280000    0.060000    0.008618   20.397420   
25%    3.752776e+06    1.810000    0.100000    0.496190   22.448135   
50%    9.705130e+06    2.410000    0.400000    2.223796   25.156990   
75%    2.791973e+07    4.095000    1.300000    6.589156   26.497575   
max    1.197070e+09    7.590000   25.900000   48.702062   28.456980   

                 GDP  BMI_female        life  child_mortality  
count     139.000000  139.000000  139.000000       139.000000  
mean    16638.784173  126.701914   69.602878        45.097122  
std     19207.299083    4.471997    9.122189        45.724667  
min       588.000000  117.375500   45.200000         2.700000  
25%      2899.000000  123.232200   62.200000         8.100000  
50%      9938.000000  126.519600   72.000000        24.000000  
75%     23278.500000  130.275900   76.850000        74.200000  
max    126076.000000  135.492000   82.600000       192.000000

In [79]:
data.isnull() # tells if null value or not

population  fertility    HIV    CO2  BMI_male    GDP  BMI_female   life  \
0         False      False  False  False     False  False       False  False   
1         False      False  False  False     False  False       False  False   
2         False      False  False  False     False  False       False  False   
3         False      False  False  False     False  False       False  False   
4         False      False  False  False     False  False       False  False   
..          ...        ...    ...    ...       ...    ...         ...    ...   
134       False      False  False  False     False  False       False  False   
135       False      False  False  False     False  False       False  False   
136       False      False  False  False     False  False       False  False   
137       False      False  False  False     False  False       False  False   
138       False      False  False  False     False  False       False  False   

     child_mortality  Region  
0              False   False  
1              False   False  
2              False   False  
3              False   False  
4              False   False  
..               ...     ...  
134            False   False  
135            False   False  
136            False   False  
137            False   False  
138            False   False  

[139 rows x 10 columns]

In [80]:
data.isnull().sum() #sum all the null values

population         0
fertility          0
HIV                0
CO2                0
BMI_male           0
GDP                0
BMI_female         0
life               0
child_mortality    0
Region             0
dtype: int64

In [81]:
data.dtypes.value_counts() #returns count of every dsta types

float64    9
object     1
dtype: int64

In [87]:
data.describe().loc[["min","max"]]# retuens max and min

population  fertility    HIV        CO2  BMI_male       GDP  \
min  2.773150e+05       1.28   0.06   0.008618  20.39742     588.0   
max  1.197070e+09       7.59  25.90  48.702062  28.45698  126076.0   

     BMI_female  life  child_mortality  
min    117.3755  45.2              2.7  
max    135.4920  82.6            192.0

In [121]:
d=data.columns[data.dtypes=="float64"]
d

Index(['population', 'fertility', 'HIV', 'CO2', 'BMI_male', 'GDP',
       'BMI_female', 'life', 'child_mortality'],
      dtype='object')

In [101]:
import pandas as pd
a=pd.read_csv("googleplaystore.csv")

In [104]:
a.size

140933

In [106]:
a.shape


(10841, 13)

In [109]:
a.head(6)

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   
5                         Paper flowers instructions  ART_AND_DESIGN     4.4   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   
5     167  5.6M      50,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   
5               Art & Design    March 26, 2017                 1.0   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up  
5    2.3 and up

In [110]:
a.tail(4)

App             Category  \
10837               Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                         Parkinson Exercices FR              MEDICAL   
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating             Genres      Last Updated         Current Ver  \
10837       Everyone          Education      July 6, 2018                 1.0   
10838       Everyone            Medical  January 20, 2017                 1.0   
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device   
10840       Everyone          Lifestyle     July 25, 2018  Varies with device   

              Android Ver  
10837          4.1 and up  
10838          2.2 and up  
10839  Varies with device  
10840  Varies with device

In [111]:
a.sample(10)

App            Category  \
5761                                     AirWatch Agent            BUSINESS   
5458                                         AP Planner              FAMILY   
6605                                              MI-BP  HEALTH_AND_FITNESS   
4341                               Dialer theme Droid L     PERSONALIZATION   
897                                       Regal Cinemas       ENTERTAINMENT   
6243                                    B'H BURGER HEIM           LIFESTYLE   
1179  DELISH KITCHEN - FREE recipe movies make food ...      FOOD_AND_DRINK   
8758                            Anti-virus Dr.Web Light               TOOLS   
9005                                   DW Contacts Wear               TOOLS   
8049                                              CX-37              FAMILY   

      Rating  Reviews                Size      Installs  Type Price  \
5761     3.1    20973                 31M    5,000,000+  Free     0   
5458     2.9       45                1.3M        5,000+  Free     0   
6605     5.0        1                 12M           50+  Free     0   
4341     4.3     1734                2.8M      100,000+  Free     0   
897      4.3    32732  Varies with device    1,000,000+  Free     0   
6243     NaN        0                 20M           10+  Free     0   
1179     4.6    32997                 13M    1,000,000+  Free     0   
8758     4.5  1094094  Varies with device  100,000,000+  Free     0   
9005     4.2       37                2.2M        5,000+  Free     0   
8049     3.9       13                 12M        1,000+  Free     0   

     Content Rating            Genres    Last Updated         Current Ver  \
5761       Everyone          Business  August 1, 2018            8.2.0.84   
5458       Everyone         Education  August 3, 2015                 1.1   
6605       Everyone  Health & Fitness   April 9, 2018           1.0.8.506   
4341     Mature 17+   Personalization   April 2, 2016                 4.0   
897        Everyone     Entertainment   July 19, 2018  Varies with device   
6243       Everyone         Lifestyle    May 26, 2016                 1.0   
1179       Everyone      Food & Drink  August 4, 2018               2.2.7   
8758       Everyone             Tools   July 10, 2018  Varies with device   
9005       Everyone             Tools   March 9, 2015             0.0.0.2   
8049       Everyone            Casual    May 30, 2016               1.3_4   

             Android Ver  
5761          4.0 and up  
5458          2.1 and up  
6605          5.0 and up  
4341        4.0.3 and up  
897   Varies with device  
6243          4.0 and up  
1179          4.1 and up  
8758  Varies with device  
9005          4.0 and up  
8049          3.0 and up

In [115]:
a.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [119]:
a.dtypes.value_counts()

object     12
float64     1
dtype: int64

In [127]:
a.describe()

Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [133]:
a.describe().loc[["count","mean","std"]]

Rating
count  9367.000000
mean      4.193338
std       0.537431

In [134]:
a.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0      False     False   False    False  False     False  False  False   
1      False     False   False    False  False     False  False  False   
2      False     False   False    False  False     False  False  False   
3      False     False   False    False  False     False  False  False   
4      False     False   False    False  False     False  False  False   
...      ...       ...     ...      ...    ...       ...    ...    ...   
10836  False     False   False    False  False     False  False  False   
10837  False     False   False    False  False     False  False  False   
10838  False     False    True    False  False     False  False  False   
10839  False     False   False    False  False     False  False  False   
10840  False     False   False    False  False     False  False  False   

       Content Rating  Genres  Last Updated  Current Ver  Android Ver  
0               False   False         False        False        False  
1               False   False         False        False        False  
2               False   False         False        False        False  
3               False   False         False        False        False  
4               False   False         False        False        False  
...               ...     ...           ...          ...          ...  
10836           False   False         False        False        False  
10837           False   False         False        False        False  
10838           False   False         False        False        False  
10839           False   False         False        False        False  
10840           False   False         False        False        False  

[10841 rows x 13 columns]

In [137]:
a.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [150]:
a.nunique()# returns nof values in a colum

App               9660
Category            34
Rating              40
Reviews           6002
Size               462
Installs            22
Type                 3
Price               93
Content Rating       6
Genres             120
Last Updated      1378
Current Ver       2832
Android Ver         33
dtype: int64